spring.application.name=demo
spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.github.scope=read:user,user:email

jwt.expiration=604800000

twitter.client-id=
twitter.client-secret=
twitter.redirect-uri=
